spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "com.example.domain"

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cache:
  redis:
    time-to-live: ${REDIS_TTL}

jwt:
  secret: f71ba1263e7217d844fc32a45794b04a9d6f139320cfad785707f80b72d7b39841796e2b65e2f7cffd47cbc5620ee34d8127054f06ce98cb2195f92b5d1b6642
  refresh:
    expiration: 2592000000
    max-count: 5
  access:
    expiration: 86400000